#Cmdlets to connect to vSphere server and export a VM
#
# The requirements for this script to work are the following:
#
# * Requires PowerCLI to be installed on the machine the script is being ran from.
# * vm-Tools / open-VM-Tools need to be installed on the guest OS (the VM).
# * The VM needs to be powered on (will add to the script at a future date for error checking).
# *  
#
# An example path would be "C:\_vmware\win11-client-01\" without quotes.
#
Write-Host "`n"
Write-Host "This script allows a a VM to be exported from vmWare." -foregroundcolor Green -backgroundcolor Black
Write-Host "`n"
Write-Host -foregroundcolor Red -backgroundcolor Black "===================================================================="
Write-Host -foregroundcolor Red -backgroundcolor Black "!! NOTE: THIS SCRIPT WILL SHUT DOWN THE VM THAT IS BEING EXPORTED !!"
Write-Host -foregroundcolor Red -backgroundcolor Black "===================================================================="
Write-Host "`n"
Write-Host "-- Notes about the script --"
Write-Host "`n"
Write-Host "* vmTools / open-VM-Tools need to be installed on the guest OS (the VM)"
Write-Host "* The VM needs to be powered on"
Write-Host "`n"
$confirmation = Read-Host "Press Y to proceed or any other key to exit"

if ($confirmation -eq 'y') {
    # proceed
    Write-Host "`n"
    Write-Host "================" -foregroundcolor Green -backgroundcolor Black
    Write-Host "Running Script." -foregroundcolor Green -backgroundcolor Black
    Write-Host "================" -foregroundcolor Green -backgroundcolor Black
    Write-Host "`n"
}
if ($confirmation -ne 'y') {
    Write-Host "`n"
    Write-Host "================" -foregroundcolor Red -backgroundcolor Black
    Write-Host "Stopping Script." -foregroundcolor Red -backgroundcolor Black
    Write-Host "================" -foregroundcolor Red -backgroundcolor Black
    Write-Host "`n"

    Break Script

}

$esxServerName = Read-Host -Prompt 'Input the name of the vSphere / ESXi server.'
Write-Host "`n"

Write-Host "`n"
Write-Host "==========================================================" -foregroundcolor Yellow -backgroundcolor Black
Write-Host "         The script will now ask for credentials.         " -foregroundcolor Yellow -backgroundcolor Black
Write-Host "==========================================================" -foregroundcolor Yellow -backgroundcolor Black
Write-Host "`n"
Write-Host "Connecting to vmWare host." -foregroundcolor green -backgroundcolor black


# Connect to VMware host
Write-Host "`n"
Connect-VIServer $esxServerName
Write-Host "`n"

#Query list of VMs
Write-Host "===================" -foregroundcolor Blue -backgroundcolor black
Write-Host "VM(s) on this host." -foregroundcolor White -backgroundcolor black
Write-Host "===================" -foregroundcolor Blue -backgroundcolor black
Get-VM | Sort-Object | Format-Table -Property Name,PowerState
$esxVMName = Read-Host -Prompt 'Input the name of the VM you wish to export.'

# Shut down the VM if the VM is not shut off
Write-Host "`n"
Get-VM -Name $esxVMName | Shutdown-VMGuest -Confirm:$false
Write-Host "Shutting down VM $esxVMName" -foregroundcolor Yellow -backgroundcolor black
Write-Host "`n"

#Adding wait timer so the VM can shut down
Start-Sleep -Seconds 15

#Save location for VM on the computer the script is running from
$vmSaveLocation = Read-Host -Prompt 'Input the path where you wish to save the .OVF file generated by vmWare.'

# Export an OVF of the VM
Get-VM -Name $esxVMName | Export-VApp -Destination $vmSaveLocation -Format OVF -Force
Write-Host "`n"

Write-Host $esxVMName "has been successfully exported to $vmSaveLocation\$esxVMName!" -foregroundcolor green -backgroundcolor black
Write-Host "`n"
$confirmation2 = Read-Host "Do you wish to power $esxVMName back on?"

#Providing choice to power the VM back on
if ($confirmation2 -eq 'y') {
    # proceed
    Write-Host "`n"
    Write-Host "============================================" -foregroundcolor green -backgroundcolor black
    Write-Host "$esxVMName is powering back on." -foregroundcolor Green -backgroundcolor Black
    Write-Host "============================================" -foregroundcolor green -backgroundcolor black
    Write-Host "`n"

    Start-VM -VM $esxVMName -Confirm:$false
}

if ($confirmation2 -ne 'y') {
    Write-Host "`n"
    Write-Host "=============================================" -foregroundcolor Yellow -backgroundcolor Black
    Write-Host "$esxVMName will stay off." -foregroundcolor Yellow -backgroundcolor Black
    Write-Host "=============================================" -foregroundcolor Yellow -backgroundcolor Black
    Write-Host "`n"

    Break Script
}