#Cmdlets to connect to vSphere server and export a VM
#
# The requirements for this script to work are the following:
#
# * vmTools needs to be installed on the guest OS (the VM)
# * The VM needs to be powered on (will add to the script at a future date for error checking)
# *  
#
# An example path would be "C:\_vmware\win11-client-01\" without quotes.
#
Write-Host "`n"
Write-Host "This script allows a a VM to be exported from vmWare." -foregroundcolor green -backgroundcolor black
Write-Host "`n"
Write-Host -foregroundcolor Red -backgroundcolor Black "===================================================================="
Write-Host -foregroundcolor Red -backgroundcolor Black "!! NOTE: THIS SCRIPT WILL SHUT DOWN THE VM THAT IS BEING EXPORTED !!"
Write-Host -foregroundcolor Red -backgroundcolor Black "===================================================================="
Write-Host "`n"
Write-Host "-- Notes about the script --"
Write-Host "`n"
Write-Host "* vmTools needs to be installed on the guest OS (the VM)"
Write-Host "* The VM needs to be powered on"
Write-Host "`n"
$confirmation = Read-Host "Press ""Y"" to proceed or any other key to exit"
Write-Host "" -foregroundcolor White -BackgroundColor Black

if ($confirmation -eq 'y') {
    # proceed
    Write-Host "`n"
    Write-Host "================" -foregroundcolor green -backgroundcolor black
    Write-Host "Running Script." -foregroundcolor green -backgroundcolor black
    Write-Host "================" -foregroundcolor green -backgroundcolor black
    Write-Host "`n"
}
if ($confirmation -ne 'y') {
    Write-Host "`n"
    Write-Host "================" -foregroundcolor red -backgroundcolor black
    Write-Host "Stopping Script." -foregroundcolor red -backgroundcolor black
    Write-Host "================" -foregroundcolor red -backgroundcolor black
    Write-Host "`n"
    Break Script

}

$esxServerName = Read-Host -Prompt 'Input the name of the vSphere / ESXi server.'

Write-Host "`n"
Write-Host "==========================================================" -foregroundcolor yellow -backgroundcolor black
Write-Host "         The script will now ask for credentials.         " -foregroundcolor yellow -backgroundcolor black
Write-Host "==========================================================" -foregroundcolor yellow -backgroundcolor black
Write-Host "`n"
Write-Host "Connecting to vmWare host." -foregroundcolor green -backgroundcolor black


# Connect to VMware host
Write-Host "`n"
Connect-VIServer $esxServerName
Write-Host "`n"

#Query list of VMs
Write-Host "===================" -foregroundcolor Blue -backgroundcolor black
Write-Host "VM(s) on this host." -foregroundcolor White -backgroundcolor black
Write-Host "===================" -foregroundcolor Blue -backgroundcolor black
Get-VM | Sort-Object | Format-Table -Property Name,PowerState
$esxVMName = Read-Host -Prompt 'Input the name of the VM you wish to export.'

# Shut down the VM if the VM is not shut off
Write-Host "`n"
Get-VM -Name $esxVMName | Shutdown-VMGuest -Confirm:$false
Write-Host "Shutting down VM $esxVMName" -foregroundcolor green -backgroundcolor black

#Adding wait timer so the VM can shut down
Start-Sleep -Seconds 30

#Save location for VM on the computer the script is running from
$vmSaveLocation = Read-Host -Prompt 'Input the path where you wish to save the .OVF file generated by vmWare.'

# Export an OVF of the VM
Get-VM -Name $esxVMName | Export-VApp -Destination $vmSaveLocation -Format OVF -Force